import React, { useState } from "react";
import { Loader2, Sparkles, Send } from "lucide-react";

const MAX_LENGTH = 1000;

export default function MealForm({ onSubmit, loading = false }) {
  const [text, setText] = useState("");
  const [error, setError] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();

    const trimmedText = text.trim();

    if (!trimmedText) {
      setError("Please describe what you ate.");
      return;
    }

    if (trimmedText.length > MAX_LENGTH) {
      setError(
        `Meal description must be ${MAX_LENGTH} characters or less.`
      );
      return;
    }

    setError("");
    onSubmit(trimmedText);
    setText("");
  };

  const handleChange = (e) => {
    const value = e.target.value;

    setText(value);

    if (error) {
      setError("");
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      className="bg-cream-100/60 p-5 sm:p-6 rounded-2xl border border-cream-200/90"
    >
      <div className="flex items-center gap-2 mb-3">
        <Sparkles className="w-4 h-4 text-clay-500" />
        <h3 className="font-display font-bold text-ink-900 text-sm sm:text-base">
          Describe what you ate
        </h3>
      </div>

      <textarea
        value={text}
        onChange={handleChange}
        placeholder="e.g. 2 chapatis, 1 cup paneer tikka masala, mixed cucumber & tomato salad"
        rows={4}
        maxLength={MAX_LENGTH}
        disabled={loading}
        required
        className="w-full p-4 mb-2 border border-cream-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-forest-100 focus:border-forest-500 transition-colors text-ink-900 placeholder-ink-400 text-sm resize-none disabled:bg-cream-100 disabled:cursor-not-allowed bg-cream-50"
      />

      <div className="flex justify-between items-center mb-4">
        {error ? (
          <p className="text-xs text-red-600 font-medium">{error}</p>
        ) : (
          <p className="text-xs text-ink-400">
            Including portion sizes yields significantly more accurate calculations.
          </p>
        )}

        <span
          className={`text-xs font-medium ${
            text.length >= MAX_LENGTH ? "text-red-500" : "text-ink-400"
          }`}
        >
          {text.length}/{MAX_LENGTH}
        </span>
      </div>

      <button
        type="submit"
        disabled={loading || !text.trim()}
        className="w-full flex justify-center items-center gap-2 bg-forest-700 hover:bg-forest-800 active:bg-forest-900 text-white font-semibold px-5 py-3.5 rounded-xl transition-all duration-200 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed text-sm"
      >
        {loading ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            <span>Analyzing meal with AI...</span>
          </>
        ) : (
          <>
            <span>Analyze Meal Now</span>
            <Send className="w-3.5 h-3.5" />
          </>
        )}
      </button>

      <p className="text-[11px] text-ink-400 text-center mt-3">
        Values generated by Dietly AI are estimations for daily mindfulness.
      </p>
    </form>
  );
}
