// models/Meal.js

import mongoose from "mongoose";

const mealSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    name: {
      type: String,
      required: true, // e.g. "Paneer Tikka" or "Oatmeal Smoothie"
    },
    ingredients: {
      type: [String], // e.g. ["Paneer", "Yogurt", "Spices"]
      default: [],
    },
    recipe: {
      type: String, // short description or instructions
    },
    calories: {
      type: Number, // optional, for tracker integration
    },
    mealType: {
      type: String,
      enum: ["Breakfast", "Lunch", "Dinner", "Snack"],
      default: "Lunch",
    },
    aiGenerated: {
      type: Boolean,
      default: false, // true if generated by AI suggestion
    },
  },
  { timestamps: true }
);

export default mongoose.model("Meal", mealSchema);
